openapi: 3.0.0
info:
  version: 1.0.0
  title: Psychic API
  description: The API reference for Psychic's hosted service
servers:
- url: https://api.psychic.dev
#----------------PATHS---------------
paths:
  /get-connections:
    post:
      description: Fetches all Connections and their associated metadata
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              required:
                - filter
              properties:
                filter:
                  type: object
                  required:
                    - account_id
                  properties:
                    connector_id:
                      type: string
                    account_id:
                      type: string
      responses:
        '200':
          description: Successfully retrieved a list of connections
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Connection"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /get-connector-status:
    post:
      description: Returns whether a connector is enabled and all accounts connected to it
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - connector_id
              properties:
                connector_id:
                  type: string
      responses:
        '200':
          description: Successfully retrieved a connector
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      is_enabled: 
                        type: boolean
                      connections: 
                        type: array
                        items:
                          $ref: "#/components/schemas/Connection"          
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /get-documents:
    post:
      description: Returns all Documents for a given account and connector
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - account_id
              properties:
                account_id:
                  type: string
                  description: The Account ID to get documents for.
                connector_id:
                  type: string
                  description: The Connector ID to get documents from. If not provided, will attempt to fetch documents from all Connectors with at least one connection.
                chunked:
                  type: boolean
                  description: Whether Documents should be returned as chunks. Chunks are fragments of a Document that's split semantically to keep similar content together. This is useful for ensuring content can fit inside the limited context window of a LLM.
                min_chunk_size:
                  type: integer
                  description: The minimum size of a chunk in characters. If not proivded, will default to 500 characters.
                max_chunk_size:
                  type: integer
                  description: The maxium size of a chunk in characters. If not proivded, will default to 1500 characters.
      responses:
        '200':
          description: Successfully retrieved documents
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetDocumentsResponse"      
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /get-conversations:
    post:
      description: Returns all Conversations for a given account and connector
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - connector_id
                - account_id
              properties:
                connector_id:
                  type: string
                account_id:
                  type: string
                oldest_timestamp:
                  type: integer
                  description: How far back to retrieve messages. Will retrieve messages from the past 24 hours if not provided.
      responses:
        '200':
          description: Successfully retrieved Messages
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetConversationsResponse"     
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /get-tickets:
    post:
      description: Returns all Tickets for a given account and connector
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - connector_id
                - account_id
              properties:
                connector_id:
                  type: string
                account_id:
                  type: string
                oldest_timestamp:
                  type: integer
                  description: How far back to retrieve messages. Will retrieve messages from the past 24 hours if not provided.
      responses:
        '200':
          description: Successfully retrieved Tickets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetTicketsResponse"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /ask-question:
    post:
      description: Uses vector based retrieval to answer a question using connected Documents as context. Takes a long time to run so a limit of 350,000 tokens worth of context is enforced.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
                - account_id
                - openai_api_key
              properties:
                question:
                  type: string
                  description: The question to ask. Should be given as a query ending in "?" or a request.
                connector_ids:
                  type: array
                  items:
                    type: string
                  description: A list of `connector_id`s to use as context. If empty, will attempt to use Documents from all data sources with at least one Connection.
                openai_api_key:
                  type: string
                  description: An OpenAI API key. used to generate embeddings and request completions from OpenAI's API.
                account_id:
                  type: string
                  description: The Account to search through. The `ask-question` endpoint can use only Documents belonging to the same Account as context.
      responses:
        '200':
          description: Successfully returned a response to the question
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuestionResponse"      
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
#----------------COMPONENTS---------------
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Connection:
      type: object
      required:
        - account_id
        - connector_id
      properties:
        account_id:
          type: string
        connector_id:
          type: string
        metadata:
          type: object
    GetDocumentsResponse:
      type: object
      required:
        - documents
      properties:
        documents:
          type: array
          items:
            $ref: "#/components/schemas/Document"
        next_page_cursor:
          type: string
          description: A cursor to use to get the next page of documents. If not provided, there are no more pages.
    Document:
      type: object
      required:
        - title
        - content
        - uri
      properties:
        title:
          type: string
          description: The title of the source document.
        content:
          type: string
          description: The text content of the document, provided as HTML. If chunked is true, will return fragments of the source document.
        uri:
          type: object
          description: A unique URL or ID that identifies the source document.
    GetConversationsResponse:
      type: object
      required:
        - messages
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
        next_page_cursor:
          type: string
          description: A cursor to use to get the next page of messages. If not provided, there are no more pages.
    Message:
      type: object
      required:
        - content
      properties:
        id:
          type: string
        content:
          type: string
        uri:
          type: string
    MessageSender:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    GetTicketsResponse:
      type: object
      required:
        - tickets
      properties:
        tickets:
          type: array
          items:
            $ref: "#/components/schemas/Document"
        next_page_cursor:
          type: string
          description: A cursor to use to get the next page of tickets. If not provided, there are no more pages.      
    QuestionResponse:
      type: object
      properties:
        answer:
          type: string
        sources:
          type: array
          items:
            type: string
    BadRequest:
      type: object
      properties:   
        message:
          type: string
security:
  - BearerAuth: []